stages:
  # - lint
  - build
  # - test
  - deploy

variables:
  IMAGE: $CI_REGISTRY_IMAGE/
  TAG: $CI_COMMIT_REF_SLUG

build:
  stage: build
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker-compose build
    - docker-compose push
  only:
    - staging
    - production

staging:
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG.$APPS_DOMAIN
  tags:
    - manager
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker stack deploy $CI_COMMIT_REF_SLUG -c docker-compose.yml
  only:
    - staging

production:
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$APPS_DOMAIN
  tags:
    - manager
  stage: deploy
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f docker-compose.yml -f docker-compose.production.yml config > docker-compose.deploy.yml
    - docker stack deploy $CI_COMMIT_REF_SLUG -c docker-compose.deploy.yml
  only:
    - production
