version: '3.2'

services:
  nginx:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.backend=${TAG}-site"
        - "traefik.frontend.rule=Host: synko.com.br, www.synko.com.br"
